apiVersion: v1
name: alt-svc
version: 1.0.21
kubeVersion: ">=1.9.0-0"
description: An alt-svc is alert management service, provides APIs to access alert info and set up a rule engine to check condition for publish notification.
keywords:
- Node.js
- server
- microservices
- amd64
- ppc64le
- Alarm
- IIoT
- ICP
- IKS
- Beta
home: https://github.com/heretse/environment-merciiot-staging
maintainers:
- name: Winston_hsieh
  email: Winston_hsieh@gemteks.com
icon: https://avatars3.githubusercontent.com/u/5375661?s=200&v=4
appVersion: "1.0"
tillerVersion: ">=2.8.0"
