apiVersion: v1
name: am-svc
version: 1.0.29
description: An am-svc is account management service, provides APIs to access user info and administration.
keywords:
- Node.js
- server
- microservices
- amd64
- ppc64le
- Account
- IIoT
- ICP
- IKS
- Beta
home: https://github.com/heretse/environment-merciiot-staging
maintainers:
- name: Winston_hsieh
  email: Winston_hsieh@gemteks.com
icon: https://avatars3.githubusercontent.com/u/5375661?s=200&v=4
appVersion: "1.0"
tillerVersion: ">=2.8.0"
