# Default values for mysqldb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: mysqldb

replicaCount: 1

image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: mysqldb
  labels:
  annotations:
  type: ClusterIP
  externalPort: 3306
  internalPort: 3306
  nodePort:
  
ingress:
  enabled: false
  host:
  - chart-example.local
  tls:

extraEnv:
extraVolumeMounts:
extraContainers:
extraVolumes:

resources:  
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
#  kubernetes.io/hostname: 10.5.88.24

tolerations: []

tcpSocket:
    port: 3306

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

#nodeAffinity
arch: amd64

# Annotations to be added to mysqldb pods
podAnnotations:
  productName: "MySQLDB Service"
  productID: "merciiot-mysqldb-svc"
  productVersion: "v1.0.0"