# Default values for report-svc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: report-svc

replicaCount: 1

image:
  repository: 10.103.74.159:5000/merciiot/report-svc
  tag: 1.0.28
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: report-svc
  labels:
  annotations:
  type: NodePort
  externalPort: 1880
  internalPort: 1880
  nodePort: 31889

ingress:
  enabled: false
  host:
  - chart-example.local
  tls:

extraEnv:
extraVolumeMounts:
extraContainers:
extraVolumes:

resources:  
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
#  kubernetes.io/hostname: 10.5.88.24

tolerations: []

probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10

#nodeAffinity
arch: amd64

# Annotations to be added to report-svc pods
podAnnotations:
  productName: "Report Service"
  productID: "merciiot-report-svc"
  productVersion: "v1.0.0"