apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: merc-packet-svc-clusterrole
rules:
- apiGroups:
  - extensions
  resourceNames:
  - merc-packet-svc-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use